language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - "node_modules"
script: yarn run unit-test:coverage
after_success:
  # Send coverage data to coveralls.
  - yarn run unit-test:report
