language: node_js
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - "node_modules"
script: yarn run ci-test
after_success:
  # Send coverage data to coveralls.
  - yarn run unit-test:report
